import assert from "node:assert/strict";
import test from "node:test";
import { NextRequest } from "next/server";
process.env.BACKEND_API_BASE_URL="http://backend.test/api/v1";
const context={params:Promise.resolve({patientId:"p-1"})};
function request(body:string,csrf=true){return new NextRequest("http://localhost:3010/api/staff/patients/p-1/link-requests",{method:"POST",headers:{"Content-Type":"application/json",host:"localhost:3010",origin:"http://localhost:3010",...(csrf?{cookie:"clinica_serena_csrf=csrf-cookie; clinica_serena_staff_session=opaque-staff","x-csrf-token":"csrf-cookie"}:{})},body});}
test("CSRF ausente se rechaza antes de leer JSON",async()=>{const{POST}=await import("../src/app/api/staff/patients/[patientId]/link-requests/route");const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error();}) as typeof fetch;try{const response=await POST(request("{invalid",false),context);assert.equal(response.status,403);assert.equal(calls,0);}finally{globalThis.fetch=original;}});
for(const[name,body]of[["ausente",{}],["false",{identityVerifiedInPerson:false}]]as const)test(`confirmacion ${name} no llega a Spring`,async()=>{const{POST}=await import("../src/app/api/staff/patients/[patientId]/link-requests/route");const original=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error();}) as typeof fetch;try{const response=await POST(request(JSON.stringify(body)),context);assert.equal(response.status,422);assert.equal(calls,0);}finally{globalThis.fetch=original;}});
test("true explicito se reenvia a Spring",async()=>{const{POST}=await import("../src/app/api/staff/patients/[patientId]/link-requests/route");const original=globalThis.fetch;const calls:Array<{url:string;init?:RequestInit}>=[];globalThis.fetch=(async(input:string|URL|Request,init?:RequestInit)=>{calls.push({url:typeof input==="string"?input:input instanceof URL?input.toString():input.url,init});return new Response("{}",{status:201,headers:{"Content-Type":"application/json"}});})as typeof fetch;try{const response=await POST(request(JSON.stringify({identityVerifiedInPerson:true})),context);assert.equal(response.status,201);assert.equal(calls.length,1);assert.equal(calls[0].url,"http://backend.test/api/v1/staff/patients/p-1/link-requests");assert.deepEqual(JSON.parse(String(calls[0].init?.body)),{identityVerifiedInPerson:true});}finally{globalThis.fetch=original;}});
