import Link from "next/link";
import { Card, StatusBadge, buttonLinkClasses } from "@/shared/components";
import { formatDate } from "@/modules/paciente-portal/format";
import { demoCheckups, demoTreatment } from "@/modules/paciente-portal/data";
import { PatientPortalHeader, SectionTitle } from "@/modules/paciente-portal/components/PatientPortalHeader";

export default function PatientCheckupsPage() {
  return <div className="space-y-7"><PatientPortalHeader actions={<Link className={buttonLinkClasses} href="/paciente/citas/nueva">Solicitar seguimiento visual</Link>} description="Progreso y chequeos de demostración, sin notas internas ni datos clínicos reales." eyebrow="Seguimiento" title="Chequeos y tratamiento" /><Card><div className="flex flex-wrap items-start justify-between gap-4"><div><StatusBadge tone="pistacho">Tratamiento de demostración</StatusBadge><h2 className="mt-4 text-2xl font-bold text-[#62727B]">{demoTreatment.name}</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#62727B]/75">{demoTreatment.description}</p></div><p className="text-3xl font-bold text-[#62727B]">{demoTreatment.progress}%</p></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-[#F8EDD2]"><div className="h-full rounded-full bg-[#62727B]" style={{ width: `${demoTreatment.progress}%` }} /></div></Card><section><SectionTitle title="Línea de tiempo ficticia" /><div className="relative ml-3 border-l-2 border-[#DDF3F1] pl-7">{demoCheckups.map((checkup, index) => <div className="relative pb-7 last:pb-0" key={checkup.id}><span aria-hidden="true" className="absolute -left-[2.1rem] top-1 h-4 w-4 rounded-full border-4 border-[#FBFCFA] bg-[#62727B]" /><Card><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold text-[#62727B]">{checkup.name}</h3><StatusBadge tone={checkup.status === "completed" ? "agua" : "crema"}>{checkup.status === "completed" ? "Completado · demo" : "Próximo · demo"}</StatusBadge></div><p className="mt-2 text-sm text-[#62727B]/75">{checkup.description}</p><p className="mt-3 text-xs font-semibold uppercase tracking-wide text-[#62727B]/60">{index === 0 ? "Siguiente recomendado" : formatDate(checkup.recommendedDate)}</p></Card></div>)}</div></section></div>;
}
